FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

RUN echo "Проверка структуры:" && ls -la /app/backend

ENV PYTHONPATH=/app/backend
ENV DJANGO_SETTINGS_MODULE=config.settings

CMD ["gunicorn", "config.wsgi", "--bind", "0.0.0.0:8000"]