# Generated by Django 5.2.1 on 2025-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('file_type', models.CharField(choices=[('text', 'Текст'), ('audio', 'Аудио'), ('video', 'Видео')], max_length=10, verbose_name='Тип файла')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Суммаризация')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное имя файла')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID пользователя')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
    ]
